package com.test.flighttestapp.models.response

data class FlightX(
    val ad: String,
    val al: String,
    val at: String,
    val atm: String,
    val bc: String,
    val bg: Bg,
    val bgid: Any,
    val cabin_class: String,
    val cbg: Cbg,
    val cbgid: Any,
    val cc: String,
    val cc_chg: Int,
    val dd: String,
    val dt: String,
    val dtm: String,
    val eq: String,
    val eq_code: String,
    val eq_quality: Int,
    val fbn: String,
    val ffk: String,
    val fn: String,
    val fr: String,
    val ft: Int,
    val halt: String,
    val halt_time: String,
    val is_lcc: Int,
    val llo: Int,
    val lo: Int,
    val oc: String,
    val ovgtf: Int,
    val ovgtlo: Int,
    val slo: Int,
    val to: String,
    val tt: Int
)